# Generated by Django 3.2 on 2021-02-04 21:28

from django.db import migrations, models
import dropkickApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=dropkickApp.models.user_directory_path)),
            ],
        ),
    ]
