# Generated by Django 3.2 on 2021-02-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropkickApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='name',
            field=models.CharField(blank=True, help_text='Enter file output name.', max_length=500),
        ),
        migrations.AddField(
            model_name='myfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
